name: Auto Start/Stop Railway Environment

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 6 AM UTC
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  manage-railway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Set Railway Token
        run: echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}" >> $GITHUB_ENV

      - name: Determine Action (Start or Stop)
        id: determine-action
        run: |
          DAY=$(date +%u) # Get current day (1=Monday, 7=Sunday)
          if [[ "$DAY" -ge 1 && "$DAY" -le 4 ]]; then
            echo "action=start" >> $GITHUB_ENV
          else
            echo "action=stop" >> $GITHUB_ENV
          fi

      - name: Start Railway Service (if needed)
        if: env.action == 'start'
        run: railway up --service=${{ secrets.RAILWAY_SERVICE_ID }}

      - name: Stop Railway Service (if needed)
        if: env.action == 'stop'
        run: railway down --service=${{ secrets.RAILWAY_SERVICE_ID }}