name: Manage Railway Service

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: "0 6 * * 0-3"  # Runs at 6 AM UTC on Sunday-Wednesday

jobs:
  manage-service:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Ensure Railway CLI compatibility

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Railway CLI
        run: npm install -g @railway/cli@latest --force

      - name: Authenticate Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: railway login --token $RAILWAY_API_TOKEN

      - name: Determine Action (Start or Stop)
        id: service_action
        run: |
          DAY_OF_WEEK=$(date +%u)  # Get current day of the week (1=Monday, 7=Sunday)
          if [[ "$DAY_OF_WEEK" -ge 1 && "$DAY_OF_WEEK" -le 3 ]]; then
            echo "action=start" >> $GITHUB_ENV
          else
            echo "action=stop" >> $GITHUB_ENV
          fi

      - name: Start Railway Service (if needed)
        if: env.action == 'start'
        run: railway up

      - name: Stop Railway Service (if needed)
        if: env.action == 'stop'
        run: railway down